# Uncomment the next line to define a global platform for your project

platform :ios, '9.0'

def thirdPartyDependencies()
    pod 'WechatOpenSDK', '~> 1.8.0'
    pod 'Weibo_SDK', '~> 3.2.0'
    
    pod 'GoogleSignIn', '~> 4.1.0'
    
    pod 'FBSDKLoginKit', '5.0.2'
    pod 'FBSDKCoreKit', '5.0.2'
    pod 'FBSDKShareKit', '5.0.2'
    
    pod 'VK-ios-sdk', '~> 1.4.0'
    
    pod 'LineSDK', '5.0.0'
end

target 'SmartSocial' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  thirdPartyDependencies()

end
